all: fork.o exec.o exit.o wait_pid.o sleep.o \
	 open.o write.o read.o lseek.o close.o \
	 lsdir.o chdir.o mkdir.o rmdir.o dup2.o

fork.o: fork.c
	cc -mi86 -com -Was-ncc -c fork.c
exec.o: exec.c
	cc -mi86 -com -Was-ncc -c exec.c
exit.o: exit.c
	cc -mi86 -com -Was-ncc -c exit.c
wait_pid.o: wait_pid.c
	cc -mi86 -com -Was-ncc -c wait_pid.c
sleep.o: sleep.c
	cc -mi86 -com -Was-ncc -c sleep.c
open.o: open.c
	cc -mi86 -com -Was-ncc -c open.c
write.o: write.c
	cc -mi86 -com -Was-ncc -c write.c
read.o: read.c
	cc -mi86 -com -Was-ncc -c read.c
lseek.o: lseek.c
	cc -mi86 -com -Was-ncc -c lseek.c
close.o: close.c
	cc -mi86 -com -Was-ncc -c close.c
lsdir.o: lsdir.c
	cc -mi86 -com -Was-ncc -c lsdir.c
chdir.o: chdir.c
	cc -mi86 -com -Was-ncc -c chdir.c
mkdir.o: mkdir.c
	cc -mi86 -com -Was-ncc -c mkdir.c
rmdir.o: rmdir.c
	cc -mi86 -com -Was-ncc -c rmdir.c
dup2.o: dup2.c
	cc -mi86 -com -Was-ncc -c dup2.c
